### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by shrocklee** [p201-sp2016/infer_structcol#24]
1. Package name  
One small thought is that using module name 'structcol_infer' would better represent the hierarchy between this module and 'structcol' module.
 
2. Model
It seems the whole model and structure of this project highly depends on the already well-established 'structcol'. I do not have any major comments on the model, and I will list few thoughts:

- The distinction between structcol and infer_structcol was not clear to me. It would be more helpful to readers if the extent covered by structcol is stated more explicitly in the ipynb file.
- Where do you send and receive photon packets? At what distance? 
- It seems the model requires measurement of exiting photon packets to calculate reflectance, which is essentially Poisson process - photon counting. This will entail uncertainty corresponding to the Poisson process. How did you propagate this uncertainty in your analysis?

3. Test run
Test runs well. However, I did not check inference done in model.ipynb because it took too much time (more than 30 minutes) in my computer.

In general, I believe the codes are very well organized and clearly written.

**Comment by AnnieStephenson** [comment]
1. Package name
This is a valid point, but I think we wanted to put infer ahead of structcol to emphasize that this package is about inference of parameters from structural color samples. 

2. Model
- I added explicit statements to the model.ipynb to make it more clear where the code relies on the structcol package. 
- The photon packets are sent directly into the sample. They are counted (received) immediately when they exit the sample. There is no distance between when they exit and when they are counted. I added some explanation to the calculating reflectance section of the model.ipynb to make this more clear.
- The scattering calculations in the model are counting photon packets to calculate reflectance, but since in the model we can exactly count each photon packet, there is no associated uncertainty. The actual reflectance measurements do not require measurement of individual photon packets. Most reflectance measurements are taken using a spectrometer that measures the intensity of the light exiting the sample, which measures large numbers of photon packets, so this would not be a Poisson process.
