### ISSUE TITLE
consider Gibbs sampling

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/infer_structcol#5]
As we discussed you might consider Gibbs sampling.  You'll probably have to write your own Gibbs sampler so that when it steps in a direction other than the volume fraction it uses the precomputed MC spectrum. But it's not too hard to write your own.  Here is a guide:
http://kieranrcampbell.github.io/gibbs-sampling-bayesian-linear-regression/

**Comment by barkls** [comment]
Now that we are switching to a parametric model for losses, the potential gains of sampling different dimensions independently are significantly reduced. Since existing samplers have already been optimized (and parallelized), they are probably faster than any Gibbs sampling routine we could write anyway. We will keep this in mind if we run into problems, but do not currently plan to implement Gibbs sampling.
